{% set name = "interpolation" %}
{% set version = "2.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/EconForge/interpolation.py/archive/v{{ version }}.tar.gz
  sha256: 35a7da36a5ff61e69a7f2321dff40c6c20282749c1e43564db86dbc8324d6bbf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9,<=3.12
    - poetry >=1.2
  run:
    - python >=3.9,<=3.12
    - numba >=0.59.1
    - scipy >=1.10.0,<2.0.0
    - packaging <22.0,>=21.3

test:
  imports:
    - interpolation
    - interpolation.smolyak
    - interpolation.splines
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/econforge/interpolation.py
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Interpolation in Python

extra:
  recipe-maintainers:
    - albop
    - jan-janssen
