{% set name = "interpolation" %}
{% set version = "2.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/EconForge/interpolation.py/archive/v{{ version }}.tar.gz
  sha256: e8383c6fb291034b803d09f947cbb3a8eac1d5e98b9d6f1b067b05ea6e6f9368

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9,<=3.12
    - poetry >=1.2
  run:
    - python >=3.9,<=3.12
    - numba >=0.59
    - scipy >=1.10
    - packaging <22.0,>=21.3

test:
  imports:
    - interpolation
    - interpolation.smolyak
    - interpolation.splines
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/econforge/interpolation.py
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Interpolation in Python

extra:
  recipe-maintainers:
    - albop
    - jan-janssen
